---
# setup-pbench-server tasks

- name: install pbench-server
  ansible.builtin.dnf:
    name: pbench-server
    state: present

- name: generate ssh key for pbench
  community.crypto.openssh_keypair:
    path: ~/.ssh/id_ed25519
    type: ed25519

- name: set authorized key from file
  ansible.builtin.authorized_key:
    user: charlie
    state: present
    key: "{{ lookup('file', '/home/charlie/.ssh/id_rsa.pub') }}"
